services:
  scribit-firmware:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: scribit-firmware-builder
    volumes:
      - ../:/workspace/source:ro  # Read-only source code
      - ./builds:/workspace/builds:rw  # Build output directory
    working_dir: /workspace
    # Default command shows help
    command: ["arduino-cli", "compile", "--help"]

# No named volumes needed - using bind mounts for simplicity